### ISSUE TITLE
When used keyboard interruption with Ctrl-c, called traceback by python.

### ISSUE THREAD

**Issue by sasukeh** [upa/deadman#5]
When used keyboard interruption with Ctrl-c, called traceback by python like following error.
I think daedoman needs exception handler. 

> upa-san
> how do you think about this?
> Is there some suggestion?

~/C/deadman ❯❯❯ ./deadman deadman.conf
Traceback (most recent call last):
  File "./deadman", line 593, in <module>
    curses.wrapper (main)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./deadman", line 558, in main
    deadman.main ()
  File "./deadman", line 478, in main
    time.sleep (PING_ALLTARGET_INTERVAL)
KeyboardInterrupt

~/C/deadman ❯❯❯ ./deadman deadman.conf
Traceback (most recent call last):
  File "./deadman", line 593, in <module>
    curses.wrapper (main)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, _args, *_kwds)
  File "./deadman", line 558, in main
    deadman.main ()
  File "./deadman", line 471, in main
    target.send ()
  File "./deadman", line 85, in send
    res = self.ping.send ()
  File "./deadman", line 186, in send
    result = commands.getoutput (pingcmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/commands.py", line 50, in getoutput
    return getstatusoutput(cmd)[1]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/commands.py", line 60, in getstatusoutput
    text = pipe.read()
KeyboardInterrupt

**Comment by upa** [comment]
I completely agree with you. It's due to my lazy work. I will implement it during this two weeks (Interop shownet hot stage starts today).

**Comment by sasukeh** [comment]
Have a fun with code and networking!!!

**Comment by upa** [comment]
One year has passed, at last, I added just an exception handler https://github.com/upa/deadman/commit/ba2e3fe592c9f83d1501f4af0ab0b8f0254b5ead !
